[package]
name = "xsd-parser"
version = "0.1.0"
authors = ["Chris Bruce <chris@lumeo.com>", "leonid.krutovsky <leonid.krutovsky@quantumsoft.ru>", "DmitrySamoylov <dmitry.samoylov@quantumsoft.ru>", "victor-soloviev <victor.soloviev@quantumsoft.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[lib]
name = "xsd_parser"
path = "src/lib.rs"

[[bin]]
name = "xsd-parser"
path = "src/bin.rs"

[dependencies]
roxmltree = "0.13.0"
Inflector = "0.11.4"
clap = "2.33.3"

[dev-dependencies]
syn = { version = "1.0.51", features = ["full"] }
log = "0.4.11"
xml-rs = "0.8.3"
yaserde = "0.4.3"
yaserde_derive = "0.4.3"
text-diff = "0.4.0"
itertools = "0.9.0"
macro-utils = { path = "../macro-utils" }
xsd-types = { path = "../xsd-types" }
num-bigint = "0.3.1"
bigdecimal = "0.2.0"
